name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'

env:
  FORCE_COLOR: 2

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn type-check
      - run: yarn lint
      - name: test with check
        run: yarn test
        continue-on-error: true
      - name: test with jest
        run: yarn jest
        continue-on-error: true
