name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: yarn-${{ hashFiles('**/yarn.lock') }}
      - run: yarn --frozen-lockfile
      - run: yarn lint
      - name: test with check
        run: yarn test
        continue-on-error: true
      - name: test with jest
        run: yarn jest
        continue-on-error: true
