name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn type-check
      - run: yarn lint
      - name: test check with check itself
        env:
          FORCE_COLOR: 2
        run: yarn test
      - name: test examples with check
        env:
          FORCE_COLOR: 2
        run: yarn test:examples
        continue-on-error: true
      - name: test examples with jest
        env:
          FORCE_COLOR: 2
        run: yarn jest:examples
        continue-on-error: true
